# Generated by Django 4.0.3 on 2022-03-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mypokemons_pokemons'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonowned',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
