# Generated by Django 4.0.3 on 2022-03-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pokemonowned_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonowned',
            name='unique_id',
            field=models.CharField(max_length=200),
        ),
    ]
