# Generated by Django 4.0.3 on 2022-03-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pokemonowned_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonowned',
            name='user',
        ),
    ]
